set repo_dir [file normalize [file join $script_dir ../..]]

add_file [file join $script_dir 0_gowin_config.sv]

add_file [file join $repo_dir design/open-source/axi/src/axi_pkg.sv]
add_file [file join $repo_dir design/open-source/reqrsp_interface/src/reqrsp_pkg.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/cf_math_pkg.sv]
add_file [file join $repo_dir design/corecomplex/cc_itf_pkg.sv]
add_file [file join $repo_dir design/corecomplex/cc_cfg_pkg.sv]

add_file [file join $repo_dir design/sophon/sophon_pkg.sv]
add_file [file join $repo_dir design/sophon/sophon.sv]
add_file [file join $repo_dir design/sophon/regfile.sv]
add_file [file join $repo_dir design/sophon/boot_code.sv]
add_file [file join $repo_dir design/sophon/sophon_top.sv]
add_file [file join $repo_dir design/sophon/sophon_axi_top.sv]
add_file [file join $repo_dir design/cust/cust.sv]
add_file [file join $repo_dir design/cust/fgpio.sv]
add_file [file join $repo_dir design/cust/snapreg.sv]
add_file [file join $repo_dir design/sophon/inst_itf_demux.sv]
add_file [file join $repo_dir design/sophon/inst_itf_arbiter.sv]
add_file [file join $repo_dir design/sophon/data_itf_demux.sv]
add_file [file join $repo_dir design/sophon/data_itf_arbiter.sv]

add_file [file join $repo_dir design/corecomplex/axi_interconnect.sv]
add_file [file join $repo_dir design/corecomplex/core_complex.sv]
add_file [file join $repo_dir design/corecomplex/crg.sv]
add_file [file join $repo_dir design/corecomplex/apb_syscfg_reg.sv]
add_file [file join $repo_dir design/corecomplex/clint.sv]
add_file [file join $repo_dir design/corecomplex/reqrsp_to_mem.sv]

add_file [file join $repo_dir design/common/std_wrap_ckinv.sv]
add_file [file join $repo_dir design/common/std_wrap_ckand.sv]
add_file [file join $repo_dir design/common/rst_sync.sv]
add_file [file join $repo_dir design/common/tcm_wrap.sv]
add_file [file join $repo_dir design/common/bw_sp_ram.sv]

add_file [file join $repo_dir design/open-source/axi/src/axi_xbar.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_to_axi_lite.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_lite_to_apb.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_dw_converter.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_dw_downsizer.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_dw_upsizer.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_atop_filter.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_burst_splitter.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_demux.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_err_slv.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_mux.sv]
add_file [file join $repo_dir design/open-source/axi/src/axi_id_prepend.sv]

add_file [file join $repo_dir design/open-source/common_cells/src/fifo_v3.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/rr_arb_tree.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/addr_decode.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/lzc.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/id_queue.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/stream_register.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/counter.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/delta_counter.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/onehot_to_bin.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/fall_through_register.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/deprecated/fifo_v2.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/isochronous_spill_register.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/spill_register.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/spill_register_flushable.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/stream_fifo.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/stream_fork.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/stream_fork_dynamic.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/stream_join.sv]
add_file [file join $repo_dir design/open-source/common_cells/src/stream_mux.sv]

add_file [file join $repo_dir design/open-source/reqrsp_interface/src/axi_to_reqrsp.sv]
add_file [file join $repo_dir design/open-source/reqrsp_interface/src/reqrsp_mux.sv]
add_file [file join $repo_dir design/open-source/reqrsp_interface/src/reqrsp_iso.sv]
add_file [file join $repo_dir design/open-source/reqrsp_interface/src/reqrsp_to_axi.sv]

add_file [file join $repo_dir design/open-source/apb_uart_sv/apb_uart_sv.sv]
add_file [file join $repo_dir design/open-source/apb_uart_sv/uart_rx.sv]
add_file [file join $repo_dir design/open-source/apb_uart_sv/uart_tx.sv]
add_file [file join $repo_dir design/open-source/apb_uart_sv/uart_interrupt.sv]
add_file [file join $repo_dir design/open-source/apb_uart_sv/io_generic_fifo.sv]

add_file [file join $script_dir gowin_rpll_10m.sv]
add_file [file join $script_dir SOPHON_FPGA_TOP.sv]
